### ISSUE TITLE
Cannot build in VS2017

### ISSUE THREAD

**Issue by edespong** [resgroup/BuildMonitor#1]
Starting from a clean slate, I get the following errors when trying to build the solution:
`2>[path]: warning MSB3283: Cannot find wrapper assembly for type library "EnvDTE80". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit.
2>[path]: warning MSB3283: Cannot find wrapper assembly for type library "EnvDTE90". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit.`

The issue seems to be a breaking change to older VS versions, [described here](https://developercommunity.visualstudio.com/content/problem/15434/cannot-find-wrapper-assembly-for-type-library-envd.html).

I solved the issue by simply deleting the references to envdte80, envdte90 and envdte100.

**Comment by edespong** [comment]
My solution can be found in [commit f104e6f](https://github.com/edespong/BuildMonitor/commit/f104e6fcbd73f85e7ed40452c302802e4295229a).

**Comment by ceddlyburge** [comment]
Hi Edes, feel free to open up pull requests for this kind of thing by the way (being as you had already fixed the problem :))

Cheers

Cedd
