### ISSUE TITLE
Proposal: Make output path configurable

### ISSUE THREAD

**Issue by edespong** [resgroup/BuildMonitor#2]
It seems like the path of the output json is hard coded to `%ROAMING%\Build Monitor\buildtimes.json`.

It would be nice if this path was configurable. My use case would be that I want to aggregate the persisted data from several developer machines on a network share (with different file names) and then do custom analysis of the build times based on this data.

**Comment by ceddlyburge** [comment]
Hi Erik

Thanks for your help on this.

I'm not available for the next couple of weeks, but I'll respond to any new things when I get back.

Cheers

Cedd

**Comment by edespong** [comment]
Cheers and happy holidays!
